### ISSUE TITLE
addMember + listInvites + acceptInvite

### ISSUE THREAD

**Issue by staltz** [ssbc/ssb-tribes2#41]
The `addMember` API should be renamed to "inviteMember".

The `start()` listener should NOT add the keys to ssb-box2, should NOT perform reindexEncrypted.

A new API `listInvites` that gives a pull-stream source of all the invites (group/add-member) you have received but haven't yet "accepted".

A new `inviteMember` API that allows you to acknowledge a group/add-member, add the keys to ssb-box2, and begin reindexEncrypted.

**Comment by Powersource** [comment]
> The addMember API should be renamed to "inviteMember".

That gives a wrong impression though, since the function *does* cryptographically add the person to the group (gives them the keys)

> A new `inviteMember` API that allows you to acknowledge a group/add-member, add the keys to ssb-box2, and begin reindexEncrypted.

Do you mean "A new `acceptInvite` API" ?

**Comment by Powersource** [comment]
To clarify for nonlinear, this issue is about making the "get added to a group-flow" into:

1. Someone adds (invites) you to a group
2. You see something like "you have been invited to 1 group", and maybe not much more info than that, maybe who invited you. you already have the keys by now, you just have to "accept" by actually using them and actually download the group content
3. you can click accept, then you download the group and can post in it etc

Should this be the flow?

**Comment by Powersource** [comment]
An alternative (current code) is:

1. Someone adds you to a group
2. You automatically download the whole group and can now post in it

**Comment by staltz** [comment]
Okay, we could keep the name `addMember`.

And yes I mean `acceptInvite` API.

> You automatically download the whole group and can now post in it

Without consent, this is pretty bad, because it's a way how users can force other users to download a lot more content, and could be an attack vector.

**Comment by Powersource** [comment]
For Alice to get added to a spam group by Mallory, Alice needs to first be replicating Mallory's invitations feed, which already is an attack vector. Although with a spammed invitations feed I guess it is harder for Mallory to get very far, since everyone replicating her would get spammed. Adding Alice to a specific group would allow Mallory to specifically target her. Unless Alice and Mallory connect directly though, someone else would also have to replicate that feed, and be able to maybe detect the spam.

If Alice doesn't automatically replicate, and instead just sees the invite at first, how much does that help her though? She will have very little info on which to judge if it's spam or not.

**Comment by staltz** [comment]
> If Alice doesn't automatically replicate, and instead just sees the invite at first, how much does that help her though? She will have very little info on which to judge if it's spam or not.

That depends on how the data for the "group door" (nonlinear's design) is received in practice. I recall @mixmix had some prior work done on "membership applications" and "doors" in Ahau so he could shed some light on how that data exists and is replicated.

**Comment by Powersource** [comment]
We discussed this in a meeting and decided to implement this for now and maybe reevaluate in the future once we've had time to try the ux in the real world.
